networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  build-cache:
  spire-assets:
  eqemu-var-log:
  mariadb-var-log:
  tailscale:

services:

  #############################################
  # tailscale gateway
  #############################################

  tailscale:
    image: tailscale/tailscale
    hostname: ${COMPOSE_PROJECT_NAME}
    networks:
      - backend
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - tailscale:/var/lib/tailscale
      - ./containers/tailscale:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_OAUTH_KEY}?ephemeral=true
      - TS_EXTRA_ARGS=--advertise-tags=${TS_TAGS} --reset
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  #############################################
  # eqemu server
  #############################################

  eqemu-server:
    restart: unless-stopped
    image: akkadius/eqemu-server:v16
    network_mode: service:tailscale
    volumes:
      - ./server:/home/eqemu/server:delegated
      - ./code:/home/eqemu/code:delegated
      - ./assets:/home/eqemu/assets:delegated
      - build-cache:/home/eqemu/.ccache/
      - spire-assets:/home/eqemu/.cache/
      - eqemu-var-log:/var/log/
    environment:
      - SPIRE_PORT=${SPIRE_PORT:-3000}
      - SPIRE_ADMIN_PASSWORD=${SPIRE_ADMIN_PASSWORD:-}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - EQEMU_DB_PASSWORD=${MARIADB_PASSWORD}
      - PEQ_EDITOR_PASSWORD=${PEQ_EDITOR_PASSWORD}
      - IP_ADDRESS=${IP_ADDRESS}
      - PORT_RANGE_HIGH=${PORT_RANGE_HIGH}
      - TZ=${TZ:-US/Central}
    tty: true
    cap_add:
      # This is needed for running perf traces
      # - CAP_SYS_ADMIN
      # For GDB traces but it has security implications
      - SYS_PTRACE
    cpu_shares: 900
    depends_on:
      tailscale:
          condition: service_healthy
      fail2ban-server:
          condition: service_started

  #############################################
  # mariadb
  #############################################

  mariadb:
    restart: unless-stopped
    build:
      context: ./containers/mariadb
      args:
        - INNODB_BUFFER_POOL_SIZE=${INNODB_BUFFER_POOL_SIZE:-256MB}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql:delegated
      - mariadb-var-log:/var/log/mysql/
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=NO
      - TZ=${TZ:-US/Central}
    networks:
      - backend
    depends_on:
      - fail2ban-mysqld

  #############################################
  # fail2ban
  #############################################

  fail2ban-server:
    restart: unless-stopped
    build:
      context: containers/fail2ban-server
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - F2B_LOG_LEVE=DEBUG
      - F2B_DB_PURGE_AGE=30d
      - F2B_MAX_RETRY=3
      - F2B_ACTION=%(action_)s
      - F2B_IPTABLES_CHAIN=DOCKER-USER
      - TZ=${TZ:-US/Central}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log:ro
      - eqemu-var-log:/eqemu/var/log/

  fail2ban-mysqld:
    restart: unless-stopped
    build:
      context: containers/fail2ban-mariadb
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - F2B_LOG_LEVE=DEBUG
      - F2B_DB_PURGE_AGE=30d
      - F2B_MAX_RETRY=3
      - F2B_ACTION=%(action_)s
      - F2B_IPTABLES_CHAIN=DOCKER-USER
      - TZ=${TZ:-US/Central}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log:ro
      - mariadb-var-log:/mariadb/var/log/mysql/

  #############################################
  # peq editor
  #############################################

  peq-editor:
    image: akkadius/peq-editor:latest
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/peq-editor:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TZ:-US/Central}
    networks:
      - backend